centos 8: move kata and qemu-vanilla stuff to 3rdparties.lst
The kata and qemu-vanilla rpm pkgs are from StarlingX_3rd_katacontainer.repo,
so moving them to 3rdparties.lst to avoid downloading errors, like

Looking for kata-containers-image-1.11.5-10.1.x86_64.rpm
--> run: sudo -E dnf download -q -c /tmp/stx_mirror_kACIYH/dnf.conf --releasever=8 --exclude='*.i686' --archlist=x86_64 kata-containers-image-1.11.5-10.1.x86_64
No package kata-containers-image-1.11.5-10.1.x86_64 available.
Exiting due to strict setting.
Error: No package kata-containers-image-1.11.5-10.1.x86_64 available.

Story: 2006729
Task: 39933

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>
Change-Id: Icc71b71f1aee6dcec1958942f13b8ce053a67cc7