Utils.sh: remove -C option from dnf download
dnf fails to download packages with the --cacheoenly (-C) option, therefore remove this option.

Refer to the dnf bug and upstream commit
https://bugzilla.redhat.com/show_bug.cgi?id=1347927
https://github.com/rpm-software-management/dnf/commit/b3b6fc6a0df308b81bd53a72ce76beb79afb8b5a

The donwloading failures are:

Looking for tpm2-tss-devel-2.0.0-4.el8.x86_64.rpm
--> run: sudo -E dnf download -q -C -c /tmp/stx_mirror_oeo5sD/dnf.conf --releasever=8 --exclude='*.i686' --archlist=x86_64 tpm2-tss-devel-2.0.0-4.el8.x86_64
Error opening file for checksum: /localdisk/designer/ytao/stx-dl/stx-tools/centos-mirror-tools/tpm2-tss-devel-2.0.0-4.el8.x86_64.rpm
Package "tpm2-tss-devel-2.0.0-4.el8.x86_64" from repository "BaseOS" has incorrect checksum
Error: Some packages have invalid cache, but cannot be downloaded due to "--cacheonly" option
Warning: tpm2-tss-devel-2.0.0-4.el8.x86_64.rpm not found
Looking for tpm2-tss-devel-2.0.0-4.el8.x86_64.rpm
--> run: sudo -E dnf download -q -C -c /tmp/stx_mirror_oeo5sD/dnf.conf --releasever=8 --exclude='*.i686' --archlist=x86_64 tpm2-tss-devel-2.0.0-4.el8.x86_64
Error opening file for checksum: /localdisk/designer/ytao/stx-dl/stx-tools/centos-mirror-tools/tpm2-tss-devel-2.0.0-4.el8.x86_64.rpm
Package "tpm2-tss-devel-2.0.0-4.el8.x86_64" from repository "BaseOS" has incorrect checksum
Error: Some packages have invalid cache, but cannot be downloaded due to "--cacheonly" option
Warning: tpm2-tss-devel-2.0.0-4.el8.x86_64.rpm not found
Error: tpm2-tss-devel-2.0.0-4.el8.x86_64.rpm not found

Story: 2006729
Task: 39933

Change-Id: Idb726dd695fbf016531b1be718107ab4773c826c

Signed-off-by: Haiqing Bai <haiqing.bai@windriver.com>
Signed-off-by: Yue Tao <yue.tao@windriver.com>
Change-Id: I68ed92491f721b9fe16c86f75f85e03fd87b8f64