fix ceph build failure: missing vi and libzstd
Since upgrade, ceph build failes with.

DEBUG util.py:587:  Error: Package: sudo-1.8.23-10.el7_9.1.tis.10.x86_64
(local_build_repo)
DEBUG util.py:587:             Requires: /usr/bin/vi
DEBUG util.py:587:  Error: Package: cmake3-3.17.5-1.el7.x86_64
(StxCentos7Distro)
DEBUG util.py:587:             Requires: libzstd.so.1()(64bit)

Add the missing packages to the distro build.

Closes-Bug: 1949112
Signed-off-by: Scott Little <scott.little@windriver.com>
Change-Id: Iab324070fd8b0f01589bc03007f627b6dce884a6