Zuul: Move jobs to debian-bullseye node
importlib_metadata, a dependency for building python pkgs,
received changes where some of its API is deprecated [1],
causing the error:

AttributeError: 'EntryPoints' object has no attribute 'get'

A possible fix is to clip the version to below 5.0,
but the debian-bullseye Zuul node already provides a compatible
version, with the added advantage of being the base OS
used for STX, increasing reliability for the tests.

Refs:
[1] https://importlib-metadata.readthedocs.io/en/latest/history.html#v5-0-0

Test Plan:
pass - Run tox tests in a debian:bullseye container

Partial-Bug: 2090865

Change-Id: Ic42caf1fd56c1d6d0f9dccc56dabfdb3c79ad6b7
Signed-off-by: Leonardo Fagundes Luz Serrano <Leonardo.FagundesLuzSerrano@windriver.com>
(adapted from commit 9f4e4b61bd2037035f47efffd2229553639a4dad)