debian: Add expect dependencies
The package expect is needed in order for the collect tool
to work, however it is not installed by default. As shown
below:

/usr/local/bin/collect: line 1455: /usr/bin/expect:
No such file or directory
Error: failed to create_collect_dir_local
for /scratch/controller-0_20220329.152233 (reason:127)

Insalled the expect tool and the following dependences:

expect  5.45.4-2+b1
tcl-expect  5.45.4-2+b1
libtcl8.6  8.6.11+dfsg-1
tcl8.6  8.6.11+dfsg-1

Test Plan
PASS: downloader -b
PASS: build-image
PASS: install iso
PASS Run the collect program

Story: 2009101
Task: 43732

Signed-off-by: Charles Short <charles.short@windriver.com>
Change-Id: I32ccf534d8c36ba487478eb8118308bb1ffa6bba