centos8: download python3-crypto and python3-ply via dnf instead of wget
The certification has expired to download python3-crypto-2.6.1-28.1.el8.x86_64.rpm and
python3-ply-3.11-2.el8.noarch.rpm via wget.

wget https://forensics.cert.org/centos/cert/8/x86_64/python3-crypto-2.6.1-28.1.el8.x86_64.rpm
--2020-12-09 06:43:48--  https://forensics.cert.org/centos/cert/8/x86_64/python3-crypto-2.6.1-28.1.el8.x86_64.rpm
Resolving forensics.cert.org (forensics.cert.org)... 192.88.209.7
Connecting to forensics.cert.org (forensics.cert.org)|192.88.209.7|:443... connected.
ERROR: The certificate of ‘forensics.cert.org’ is not trusted.
ERROR: The certificate of ‘forensics.cert.org’ has expired.

Refer to the "Install Howto" of the link below, add the yum resource of
cert-forensics-tools and then download the 2 python modules via dnf.

https://centos.pkgs.org/8/forensics-x86_64/python3-crypto-2.6.1-28.1.el8.x86_64.rpm.html

Story: 2006729
Task: 41319

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>
Change-Id: I9fb1ee536c9782cc52122fc4f79ec24c6badf9f7