CentOS 8: update the yum repositories.
A lot of packages are missed during download mirror phase due to the out
of date yum repository urls. To fix it, adding the CentOS 8.0.1905 repos to
StarlingX-Centos-8.0.repo, and updating the urls of CentOS 8.1.1911. Also
fix a hardcode ulr of CentOS 8.1.1911 in dl_other_from_centos_repo.sh.

Snapshot the downloading metadata errors

Errors during downloading metadata for repository 'StarlingX-C8.1.1911-AppStream':
  - Status code: 404 for http://mirror.centos.org/centos/8.1.1911/AppStream/x86_64/os/repodata/repomd.xml (IP: 74.120.220.234)
Error: Failed to download metadata for repo 'StarlingX-C8.1.1911-AppStream': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Errors during downloading metadata for repository 'StarlingX-C8.1.1911-BaseOS':
  - Status code: 404 for http://mirror.centos.org/centos-8/8.1.1911/BaseOS/x86_64/os/repodata/repomd.xml (IP: 66.241.106.181)
Error: Failed to download metadata for repo 'StarlingX-C8.1.1911-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Errors during downloading metadata for repository 'StarlingX-C8.1.1911-PowerTools':
  - Status code: 404 for http://mirror.centos.org/centos/8.1.1911/PowerTools/x86_64/os/repodata/repomd.xml (IP: 209.44.106.213)
Error: Failed to download metadata for repo 'StarlingX-C8.1.1911-PowerTools': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Errors during downloading metadata for repository 'StarlingX-C8.1.1911-messaging':
  - Status code: 404 for http://mirror.centos.org/centos/8.1.1911/messaging/x86_64/rabbitmq-38/repodata/repomd.xml (IP: 66.241.106.181)

All failures please refer to
http://mirror.starlingx.cengn.ca/mirror/starlingx/feature/centos8/centos/monolithic/20201123T100001Z/logs/jenkins-STX_download_mirror-1058.log

FYI, the patch can resolve most of the download issues, but not all.

Signed-off-by: Haiqing Bai <Haiqing.bai@windriver.com>
Signed-off-by: Yue Tao <yue.tao@windriver.com>

Change-Id: I705b1db8dfe91acfd45fdf802099c8ffc16240c0